---
- name: Some Tests
  hosts: localhost
  serial: 1
  become: false
  tasks:

  - name: Connect to the cluster
    include: connection.yml

  - name: Create a secret
    dcos_secret:
      path: test/secret
      value: "Hello World!"

  - name: Create a file-based secret
    dcos_secret_file:
      path: test/secret_file
      file: ./ansible.cfg

  - name: Run a Marathon application
    dcos_marathon:
      app_id: nginx
      state: present
      options:
        cpus: 0.1
        mem: 128
        instances: 1
        container:
          type: DOCKER
          docker:
            image: nginx
          portMappings:
            - containerPort: 80
              hostPort: 0
              protocol: tcp
              name: default
        networks:
          - mode: container/bridge

  - name: Ensure Spark is installed
    dcos_package:
      name: spark
      app_id: namespace/spark
      version: 2.9.0-2.4.3
      state: present
      options:
        service:
          UCR_containerizer: true
          user: nobody